<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="PNL-5CD209FSV6" failures="6" tests="6" name="Default test(failed)" time="9.612" errors="0" timestamp="2023-04-19T16:02:04 IST">
  <testcase classname="api.test.DDTest" name="testPOSTUser" time="2.319">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.test.DDTest.testPOSTUser(DDTest.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testPOSTUser -->
  <testcase classname="api.test.DDTest" name="testPOSTUser" time="1.054">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.test.DDTest.testPOSTUser(DDTest.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testPOSTUser -->
  <testcase classname="api.test.DDTest" name="testPOSTUser" time="1.098">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.test.DDTest.testPOSTUser(DDTest.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testPOSTUser -->
  <testcase classname="api.test.DDTest" name="DELETEUserbyName" time="2.029">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.test.DDTest.DELETEUserbyName(DDTest.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DELETEUserbyName -->
  <testcase classname="api.test.DDTest" name="DELETEUserbyName" time="1.027">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.test.DDTest.DELETEUserbyName(DDTest.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DELETEUserbyName -->
  <testcase classname="api.test.DDTest" name="DELETEUserbyName" time="1.049">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.test.DDTest.DELETEUserbyName(DDTest.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DELETEUserbyName -->
  <testcase classname="api.test.DDTest" name="GETUserbyName" time="0.0">
    <ignored/>
  </testcase> <!-- GETUserbyName -->
</testsuite> <!-- Default test(failed) -->
